# 1. La URL limpia (Solo lleva el protocolo, el host de Render, el puerto y el nombre de la base de datos)
spring.datasource.url=jdbc:postgresql://dpg-d8rcabflk1mc73bo8dc0-a.oregon-postgres.render.com:5432/backend_springboot_basedatos_p6_sis414

# 2. El usuario por separado
spring.datasource.username=backend_springboot_basedatos_p6_sis414_user

# 3. La contraseña por separado
spring.datasource.password=3z7zZBHCPb1WTWFRhPryyaiAT7kbqc04

# El driver se queda igual
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
